#!/usr/bin/env bash

set -e
set -u

exit_code=0
docker_flags=(--rm -v "$PWD:/testplugin" -v "$PWD/test:/home" -w /testplugin "$DOCKER_RUN_IMAGE")

echo '========================================'
echo 'Running custom linting rules'
echo '========================================'
echo 'Custom warnings/errors follow:'
echo

set -o pipefail

if [ "$NO_DOCKER" -ne 1 ]; then
    docker run "${docker_flags[@]}" test/script/custom-linting-rules . || exit_code=$?
else
    test/script/custom-linting-rules . || exit_code=$?
fi

set +o pipefail

echo
echo '========================================'
echo 'Checking for duplicate tags'
echo '========================================'
echo 'Duplicate tags follow:'
echo

set -o pipefail

if [ "$NO_DOCKER" -ne 1 ]; then
    docker run "${docker_flags[@]}" test/script/check-duplicate-tags . || exit_code=$?
else
    test/script/check-duplicate-tags . || exit_code=$?
fi

set +o pipefail

echo
echo '========================================'
echo 'Checking for invalid tag references'
echo '========================================'
echo 'Invalid tag references tags follow:'
echo

set -o pipefail

if [ "$NO_DOCKER" -ne 1 ]; then
    docker run "${docker_flags[@]}" test/script/check-tag-references || exit_code=$?
else
    test/script/check-tag-references || exit_code=$?
fi

set +o pipefail

echo '========================================'
echo 'Look for badly aligned doc tags'
echo '========================================'
echo 'Badly aligned tags follow:'
echo

set -o pipefail

if [ "$NO_DOCKER" -ne 1 ]; then
    docker run "${docker_flags[@]}" test/script/check-tag-alignment || exit_code=$?
else
    test/script/check-tag-alignment || exit_code=$?
fi

set +o pipefail

exit $exit_code
