#!/usr/bin/env bash

set -e
set -u

docker_flags=(--rm -w /testplugin -v "$PWD/test:/home")
# Mount most directories, but definitely not .venv!
for filename in *; do
    if \
        [ "$filename" != run-tests ] \
        && [ "$filename" != Dockerfile ] \
        && [[ "$filename" != *.md ]] \
    ;then
        docker_flags+=("-v" "$PWD/$filename:/testplugin/$filename")
    fi
done
docker_flags+=("$DOCKER_RUN_IMAGE")
# We can just use the virtualenv executables as PATH only, we only need those.
docker_flags+=(env PATH=/root/.venv/bin)

set -o pipefail

exit_code=0

echo '========================================'
echo 'Running Vint to lint our code'
echo '========================================'
echo 'Vint warnings/errors follow:'
echo

docker run -a stdout "${docker_flags[@]}" vint -s autoload plugin || exit_code=$?

echo

exit "$exit_code"
