#!/usr/bin/env bash

set -eu

exit_code=0

docker_flags=(--rm -v "$PWD:/testplugin" -w /testplugin "$DOCKER_RUN_IMAGE")

echo '========================================'
echo 'Running Python checks'
echo '========================================'
echo 'tox warnings/errors follow:'
echo

tox_command='tox --workdir .tox-docker --skip-missing-interpreters=false'

set -o pipefail

if [ "$NO_DOCKER" -ne 1 ]; then
    # shellcheck disable=2086
    docker run -a stdout "${docker_flags[@]}" $tox_command || exit_code=$?
else
    $tox_command || exit_code=$?
fi

set +o pipefail

exit $exit_code
