#!/usr/bin/env bash

set -e
set -u

exit_code=0
docker_flags=(--rm -v "$PWD:/testplugin" -v "$PWD/test:/home" -w /testplugin "$DOCKER_RUN_IMAGE")

echo '========================================'
echo 'Running Vint to lint our code'
echo '========================================'
echo 'Vint warnings/errors follow:'
echo

vint='/root/.pyenv/versions/3.10.10/bin/vint'

set -o pipefail
docker run -a stdout "${docker_flags[@]}" "$vint" -s autoload plugin || exit_code=$?
set +o pipefail
echo

exit "$exit_code"
