" vint: -ProhibitSetNoCompatible

" Load builtin plugins
" We need this because run_vim.sh sets -i NONE
if has('win32')
    set runtimepath=$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,C:\vader,C:\testplugin
else
    set runtimepath=/home/vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,/testplugin,/vader
endif

if !has('win32')
    set shell=/bin/sh
    set shellcmdflag=-c
endif

set nocompatible
" The encoding must be explicitly set for tests for Windows.
execute 'set encoding=utf-8'
